# remote_theme: pages-themes/leap-day@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
title: Energy Sim Project
description: A dissertation project in Civil Infrastructure Systems @ the University of Delaware
